### ISSUE TITLE
JWT.JwtDecoder.Validate ArgumentNullException

### ISSUE THREAD

**Issue by Altafard** [jwt-dotnet/jwt#277]
I have a code
```c#
using var issuerRsaKeyReader = new StringReader(IssuerPrivateRSAKey);

var issuerPem = new PemReader(issuerRsaKeyReader)
    .ReadObject() as AsymmetricCipherKeyPair;

var issuerPublicKey = RSA.Create(
    DotNetUtilities.ToRSAParameters(issuerPem.Public as RsaKeyParameters));
var issuerPrivateKey = RSA.Create(
    DotNetUtilities.ToRSAParameters(issuerPem.Private as RsaPrivateCrtKeyParameters));

var token = new JwtBuilder()
    .WithAlgorithm(new RS256Algorithm(issuerPublicKey, issuerPrivateKey))
    .Issuer("test")
    .AddClaim("sub", "test")
    .Encode();

var payload = new JwtBuilder()
    .WithAlgorithm(new RS256Algorithm(issuerPublicKey))
    .MustVerifySignature()
    .Decode(token);
```

But when I try to decode token, I got an error
```c#
at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument) 
at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector) 
at JWT.JwtDecoder.Validate(JwtParts jwt, Byte[][] keys)
 at JWT.JwtDecoder.Decode(String token, Byte[][] keys, Boolean verify) in d:\a\1\s\src\JWT\JwtDecoder.cs:line 145
```

**Comment by abatishchev** [comment]
What version you're using? Please try `7.1.0-beta1` and let me know if the issue persists.

**Comment by Altafard** [comment]
This problem doesn't reproduce in version `7.1.0-beta1`. Thanks a lot!
