### ISSUE TITLE
Documentation Unclear

### ISSUE THREAD

**Issue by BlackBearFTW** [jwt-dotnet/jwt#353]
I am trying to implement this package on my web api, so I installed the asp extension package and copied this codeblock
```cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddAuthentication(options =>
                 {
                     options.DefaultAuthenticateScheme = JwtAuthenticationDefaults.AuthenticationScheme;
                     options.DefaultChallengeScheme = JwtAuthenticationDefaults.AuthenticationScheme;
                 })
            .AddJwt(options =>
                 {
                     // secrets
                     options.Keys = new[] { "GQDstcKsx0NHjPOuXOYg5MbeJ1XT0uFiwDVvVBrk" };
                     
                     // force JwtDecoder to throw exception if JWT signature is invalid
                     options.VerifySignature = true;
                 });
}

public void Configure(IApplicationBuilder app)
{
    app.UseAuthentication();
}
````

This is my utility for generating the token (and validating, but that isn't being used atm)
```cs
    public static class JsonWebTokenUtility
    {
        private readonly static JwtBuilder jwt = JwtBuilder.Create().WithAlgorithm(new HMACSHA256Algorithm()).WithSecret("HelloWorld");
        public static string Sign(Dictionary<string, object> payload)
        {
           return jwt.ExpirationTime(DateTime.Now.AddHours(8))
                      .AddClaims(payload)
                      .Encode();
        }

        public static string Validate(string token)
        {
           return jwt.MustVerifySignature().Decode(token);
        }
    }
    ```
    
    However when I use a valid token to go to an `[Authorize]` route, I still get a 401 response.
    
    My console shows this:
    ```cs
    JWT.JwtAuthenticationHandler[2]
      Error decoding JWT: This instance was constructed without validator and algorithm so cannot be used for signature validation, returning failure
      System.InvalidOperationException: This instance was constructed without validator and algorithm so cannot be used for signature validation
         at JWT.JwtDecoder.Decode(JwtParts jwt, Byte[][] keys, Boolean verify)
         at JWT.JwtDecoder.DecodeToObject[T](JwtParts jwt, Byte[][] keys, Boolean verify)
         at JWT.JwtDecoderExtensions.DecodeToObject[T](IJwtDecoder decoder, String token, Byte[][] keys, Boolean verify)
         at JWT.JwtDecoderExtensions.DecodeToObject[T](IJwtDecoder decoder, String token, String[] keys, Boolean verify)
         at JWT.JwtAuthenticationHandler.GetAuthenticationResult(String header)
info: JWT.JwtAuthenticationHandler[7]
      Bearer was not authenticated. Failure message: This instance was constructed without validator and algorithm so cannot be used for signature validation
info: JWT.JwtAuthenticationHandler[12]
      AuthenticationScheme: Bearer was challenged.
```

However the documentation is so unclear that I don't know how to fix this. What can I do?

**Comment by BlackBearFTW** [comment]
> Hi! You're right, the doc is missing something. Try this
> 
> ```c#
> jwt.WithValidator(new JwrValidator(...));
> ```
> 
> I'll see later today what can be improved in the code and/or the doc.

This should go in my startup.cs file right? Where exactly?

**Comment by abatishchev** [comment]
````c#
public static string Validate(string token)
{
    return jwt.WithValidator(new JwtValidator(...))
              .MustVerifySignature()
              .Decode(token);
}
```

**Comment by BlackBearFTW** [comment]
Okay, but the utility Verify method isn't being called from my startup.cs

**Comment by abatishchev** [comment]
What's your environment? I mean the version of ASP.NET Core.

Here's the code: https://github.com/jwt-dotnet/jwt/blob/main/src/JWT.Extensions.AspNetCore/AuthenticationAppBuilderExtensions.cs#L23

It registers all the necessary components but by some reason the DI container chooses incorrect (partial) ctor which doesn't pass the validator hence later it throws exception.

**Comment by BlackBearFTW** [comment]
.net 5 Asp.net core web api (latest stable release)

**Comment by abatishchev** [comment]
I found what's the problem. It's not about missing the validator, it's about missing algorithm factory.

The test does the following:

```c#
services.AddSingleton<IAlgorithmFactory>(new DelegateAlgorithmFactory(algorithm)); // or any other implementation
```
Another option is to use `AddJwt<TFactory>()` if you have a custom implementation of `IAlgorithmFactory`.

I'll clarify the readme.

**Comment by abatishchev** [comment]
This is a one-man show that I run in my spare time.

ASP.NET Core extensions were added quite recently so having good docs is a work in progress.

`algorithm` can be either symmetric (HMAC256, means simple hash) or asymmetric (e.g. RS256, means X.509 certificate). You should really use only **the latter**. The former is an artifact of the past.

Which one you're using?

**Comment by BlackBearFTW** [comment]
```cs
JWT.JwtAuthenticationHandler[1]
      Successfully decoded JWT, returning success
info: JWT.JwtAuthenticationHandler[12]
      AuthenticationScheme: Bearer was challenged.
```

Still getting a 401 status

```
        public void ConfigureServices(IServiceCollection services)
        {

            services.AddSingleton<IAlgorithmFactory>(new DelegateAlgorithmFactory(new HMACSHA256Algorithm())); // or any other implementation

            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtAuthenticationDefaults.AuthenticationScheme;
            })
        .AddJwt(options =>
        {
                // secrets
                options.Keys = new[] { "HelloWorld" };

                // force JwtDecoder to throw exception if JWT signature is invalid
                options.VerifySignature = true;
        });

            services.AddControllers();

            services.AddDbContext<DatabaseContext>(opt => opt.UseMySQL(Configuration.GetConnectionString("DefaultConnection")));


            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "WebshopBackendApi", Version = "v1" });
            });
        }
````

I will use `HMAC256` since I don't fully understand how `RS256` works atm.

**Comment by abatishchev** [comment]
Try to copy [this code](https://github.com/jwt-dotnet/jwt/blob/main/tests/JWT.Extensions.AspNetCore.Tests/JwtAuthenticationHandlerIntegrationTests.cs#L128) to your project and run, it should tell better why it's getting rejected.

**Comment by abatishchev** [comment]
Let's figure this out, happy to help and learn together. I'd suggest maybe to switch to a certificate-based asymmetric algorithm and make it work, rather than wasting time on insecure hash-based one.

**Comment by abatishchev** [comment]
For HMAC algorithm, the secret matters:

```c#
options.Keys = new[] { "HelloWorld" };
```

Which should match:

```c#
private readonly static JwtBuilder jwt = JwtBuilder.Create()
                                                   .WithAlgorithm(new HMACSHA256Algorithm())
                                                   .WithSecret("HelloWorld");
```
Just want to make sure they do.

**Comment by BlackBearFTW** [comment]
Yeah it does, should I do anything with https://github.com/jwt-dotnet/jwt/issues/353#issuecomment-936743494

**Comment by abatishchev** [comment]
I'm puzzled why the token is valid but the user is not authorized. Do this:

1. Download this library's source code (both Jwt and AspNetCore)
2. Removed package references from your projects
3. Add project references
4. Rebuild all
5. Debug

You'll see where it gets rejected. Makes sense?

**Comment by abatishchev** [comment]
Or try your luck with a Microsoft library for JWT auth. See if your setup will work out of the box. Or it's something else is misconfigured or missing.

**Comment by seancallinan** [comment]
```csharp
            services.AddAuthentication(opts =>
            {
                opts.DefaultAuthenticateScheme = JwtAuthenticationDefaults.AuthenticationScheme;
                opts.DefaultChallengeScheme = JwtAuthenticationDefaults.AuthenticationScheme;
            }).AddJwt(opts =>
            {
                opts.Keys = new[] { "SuperSecretKeyGoesHere" };
                opts.VerifySignature = true;

            });

            // this line is needed to give the middleware the ability to validate the signature of the token
            services.AddSingleton<IAlgorithmFactory>(new HMACSHAAlgorithmFactory());
```

**Comment by songkeith** [comment]
`
builder.Services.AddSingleton<IAlgorithmFactory>(new DelegateAlgorithmFactory(new HMACSHA256Algorithm()));

builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtAuthenticationDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtAuthenticationDefaults.AuthenticationScheme;
})
        .AddJwt(options =>
        {
            // secrets
            options.Keys = new[] { "abc123!!" };

            // force JwtDecoder to throw exception if JWT signature is invalid
            options.VerifySignature = true;
        });

var app = builder.Build();

//Note the following order and location
app.UseAuthentication();
app.UseRouting();
app.UseAuthorization();
`

**Comment by abatishchev** [comment]
@songkeith thanks for contributing a working sample. Feel free to open an issue if facing any troubles. Or contribute to the docs!

**Comment by leonardopagotto0** [comment]
> Worked it out:
> 
> ```cs
>             services.AddAuthentication(opts =>
>             {
>                 opts.DefaultAuthenticateScheme = JwtAuthenticationDefaults.AuthenticationScheme;
>                 opts.DefaultChallengeScheme = JwtAuthenticationDefaults.AuthenticationScheme;
>             }).AddJwt(opts =>
>             {
>                 opts.Keys = new[] { "SuperSecretKeyGoesHere" };
>                 opts.VerifySignature = true;
> 
>             });
> 
>             // this line is needed to give the middleware the ability to validate the signature of the token
>             services.AddSingleton<IAlgorithmFactory>(new HMACSHAAlgorithmFactory());
> ```

It works! thank you!
