### ISSUE TITLE
Unable to parse JWT Token handle data type other than String

### ISSUE THREAD

**Issue by doggy8088** [jwt-dotnet/jwt#374]
Here is the payload of my JWT token:

```json
{
  "jti": "c1c391b5-0fb0-4a98-b536-5591628b9ce4",
  "iss": "JwtAuthDemo",
  "sub": "will",
  "exp": 1644680710,
  "nbf": 1644678910,
  "iat": 1644678910,
  "roles": [
    "Admin",
    "Users"
  ],
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name": "will"
}
```

The `roles` is an array. This is used for ASP.NET Core `Roles`. If I want to use this, I can't parse this type of JWT Token. I'll get the following error:

```log
info: JWT.Extensions.AspNetCore.JwtAuthenticationHandler[2]
      Error decoding JWT: Unexpected character encountered while parsing value: [. Path 'roles', line 1, position 139., returning failure
      Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: [. Path 'roles', line 1, position 139.
         at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
         at Newtonsoft.Json.JsonTextReader.ReadAsString()
         at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract 
containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
         at JWT.Serializers.JsonNetSerializer.Deserialize[T](String json)
         at JWT.JwtDecoder.DecodeToObject[T](JwtParts jwt, Byte[][] keys, Boolean verify)
         at JWT.JwtDecoderExtensions.DecodeToObject[T](IJwtDecoder decoder, String token, Byte[][] keys, Boolean verify)
         at JWT.JwtDecoderExtensions.DecodeToObject[T](IJwtDecoder decoder, String token, String[] keys, Boolean verify)
         at JWT.Extensions.AspNetCore.JwtAuthenticationHandler.GetAuthenticationResult(String header)
info: JWT.Extensions.AspNetCore.JwtAuthenticationHandler[7]
      Bearer was not authenticated. Failure message: Unexpected character encountered while parsing value: [. Path 'roles', line 1, position 139.
```

> https://github.dev/jwt-dotnet/jwt/blob/20378ec58608119b08f7d199fb4064f2d1b0fab1/src/JWT.Extensions.AspNetCore/JwtAuthenticationHandler.cs#L120

**Comment by abatishchev** [comment]
ClaimsIdentity allows to add the same claim (role) multiple times, see https://stackoverflow.com/a/54668832/41956.

However that's not possible in JSON, each key must be unique.

**Comment by doggy8088** [comment]
I think the payload should not decoded as `Dictionary<string, string>`. It because the payload doesn't have to be identical as [Claims](https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claim.-ctor#system-security-claims-claim-ctor(system-string-system-string)).  If the items of the payload is an array, the `DefaultIdentityFactory` should parse it as separate Claims with the same key.

**Comment by abatishchev** [comment]
> because the payload doesn't have to be identical as Claims

That's the premise of the code.

> the DefaultIdentityFactory should parse it as multiple Claims with the same type.

That would require a custom serializer as it should support both `string` (default case) and `string[]` (your case) as the value. And note that it's a single key on your payload, others are regular strings.

If you'll be willing to contribute to the library - I'll be happy to help out, review and ship it asap.

**Comment by doggy8088** [comment]
I'm willing to contribute.

I have to replace the `JwtAuthenticationHandler` and `DefaultIdentityFactory`, right?

**Comment by abatishchev** [comment]
I got an idea:
I'll expose property `Type` that by default would be `Dictionary<string, string>` which you can redefine with your own, e.g. strongly-typed or `Dictionary<string, object>`. Then your custom `IIdentityFactory` will create claims from it.
I'll give it a try shortly.
