### ISSUE TITLE
TargetParameterCountException thrown by DictionaryStringObjectJsonConverter.CustomWrite()

### ISSUE THREAD

**Issue by abatishchev** [jwt-dotnet/jwt#438]
### Stacktrace

```log: System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at JWT.Serializers.Converters.DictionaryStringObjectJsonConverterCustomWrite.<>c__DisplayClass2_0.<HandleValue>b__1(PropertyInfo p) in MyProject/jwt/src/JWT/Serializers/Converters/DictionaryStringObjectJsonConverter.cs:line 121
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](TSource[] source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at JWT.Serializers.Converters.DictionaryStringObjectJsonConverterCustomWrite.HandleValue(Utf8JsonWriter writer, String key, Object objectValue) in MyProject/jwt/src/JWT/Serializers/Converters/DictionaryStringObjectJsonConverter.cs:line 119
   at JWT.Serializers.Converters.DictionaryStringObjectJsonConverterCustomWrite.Write(Utf8JsonWriter writer, Dictionary`2 value, JsonSerializerOptions options) in MyProject/jwt/src/JWT/Serializers/Converters/DictionaryStringObjectJsonConverter.cs:line 45
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteStringUsingSerializer[TValue](TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at JWT.Serializers.SystemTextSerializer.Serialize(Object obj) in MyProject/jwt/src/JWT/Serializers/SystemTextSerializer.cs:line 28
   at JWT.JwtEncoder.Encode(IDictionary`2 extraHeaders, Object payload, Byte[] key) in MyProject/jwt/src/JWT/JwtEncoder.cs:line 66
   at JWT.Builder.JwtBuilder.Encode() in MyProject/jwt/src/JWT/Builder/JwtBuilder.cs:line 263
   at WebSockets.Services.AuthService.CreateSession(User user) in MyProject/DirtyChat/Services/AuthService.cs:line 92
```

_Originally posted by @MaxLevs in https://github.com/jwt-dotnet/jwt/issues/436#issuecomment-1255363578_

**Comment by abatishchev** [comment]
**Workaround**: switch from System.Text serializer to Json.Net.

Meanwhile I'm looking into the issue.

**Comment by abatishchev** [comment]
@hartmark can you please help on this? Here's the lines throwing the exception:

https://github.com/jwt-dotnet/jwt/blob/e59150f9e203182f9957d1697b11ff09384166df/src/JWT/Serializers/Converters/DictionaryStringObjectJsonConverter.cs#L119-L121

**Comment by hartmark** [comment]
It seem to work perfectly in main-branch, see the linked PR for the test I checked in.

@MaxLevs; are you sure you tried installing the pre-release version of the jwt nuget?
https://learn.microsoft.com/en-us/nuget/create-packages/prerelease-packages#installing-and-updating-pre-release-packages

**Comment by hartmark** [comment]
Just poke me if I have misunderstood the issue :)

**Comment by MaxLevs** [comment]
Yep. I installed latest pre-release version firstly. And then replaced it with the latest commit, including the sources in the solution.

**Comment by MaxLevs** [comment]
@hartmark I figured the reason out. Try to add IEnumerable as claim value.

**Comment by hartmark** [comment]
Cool, now I have a better time to figure out where I went wrong in the implementation :)

**Comment by abatishchev** [comment]
Could you (one or another or both) please contribute a test that exposes the issue? And then maybe a fix :)

**Comment by abatishchev** [comment]
Never mind, missed you already opened #439. Thanks!

**Comment by hartmark** [comment]
It seems that the code example I stole didn't cover IEnumerables, I have added handling for that so now the test passes with a claim that is an IEnumerable.

@MaxLevs Can you please check if this fixes your issue?

**Comment by MaxLevs** [comment]
> Can you please check if this fixes your issue?

Yes. It works for me.
